name: First Workflow
on: workflow_dispatch
jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hellow GitHub!"
      - name: print goodbye
        run: echo "Done - Bye!"
        
